language: dart

sudo: false

services:
  - redis-server

install:
  - gem install coveralls-lcov

script:
  - ./tool/travis.sh

after_success:
  - coveralls-lcov --repo-token "$COVERALLS_REPO_TOKEN" var/lcov.info
